### ISSUE TITLE
Cannot compile on Mac due to hard-coded gcc path which does not exist

### ISSUE THREAD

**Issue by rbuck** [mark-moseley/linecache#13]
Here is what I get:

Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-base:
    ERROR: Failed to build gem native extension.

```
    /Users/rbuck/.rvm/rubies/ruby-1.8.7-p357/bin/ruby extconf.rb
```

creating Makefile

make
/usr/bin/gcc-4.2 -I. -I/Users/rbuck/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/rbuck/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/i686-darwin11.3.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -g -O2  -fno-common -pipe -fno-common   -c trace_nums.c
make: /usr/bin/gcc-4.2: No such file or directory

The path on a Mac for gcc is /usr/bin/gcc, without the 4.2 extension on it. Any chance you can discover the path to GCC rather than hard code it?

**Comment by zmajstor** [comment]
try this:
`ln -s gcc gcc-4.2`

http://stackoverflow.com/questions/6119153/why-do-i-get-a-bcrypt-ruby-gem-install-error
